### ISSUE TITLE
HB-UNI-Sen-TEMP-DS18B20.ino

### ISSUE THREAD

**Issue by isolhara** [jp112sdl/HB-UNI-Sen-TEMP-DS18B20#2]
Es werden immer nur die ersten 4 Sensoren übertragen. Ich habe 5 Sensoren angeschlossen. Wenn ich bei der Aufteilung der Messages  '4' und dann '0' vertausche, wird nur Sensor 5 übertragen, 1 bis 4 nicht.

**Comment by jp112sdl** [comment]
Werden im seriellen Monitor 5 Temperaturen angezeigt?
Ist die Zentrale eine CCU2 oder RaspberryMatic?

**Comment by isolhara** [comment]
Wo finde ich den seriellen Monitor. Es ist mein erstes Arduino Projekt. Es handel sich um eine RaspberryMatic Zentrale.

**Comment by jp112sdl** [comment]
https://learn.adafruit.com/adafruit-arduino-lesson-5-the-serial-monitor/the-serial-monitor

Unten rechts muss die Baudrate 57600 eingestellt werden.

**Comment by isolhara** [comment]
Es kommen nur unlesbare Zeichen

**Comment by jp112sdl** [comment]
Und wenn du auf 115200 stellst?

**Comment by jp112sdl** [comment]
Ich habe schon eine Vermutung...
Kann es sein, dass du eine 16MHz Arduino nutzt?

**Comment by isolhara** [comment]
Ich hatte keinen Zugriff mehr auf GitHub

**Comment by jp112sdl** [comment]
Ja, Github war vorhin down.

Hast du vor dem Flashen auf 8MHz gestellt?
<img width="590" alt="bildschirmfoto 2018-07-16 um 19 32 10" src="https://user-images.githubusercontent.com/18190139/42778023-1229ec00-893c-11e8-8135-33f9839e28d3.png">

**Comment by jp112sdl** [comment]
Ok - also zusammengefasst:
**8Mhz** eingestellt - seriell kommen Meldungen nur bei **115200 Baud**
In der Lib sind **57600 Baud** vorgegeben - heißt -> **du hast einen 16MHz Arduino Pro Mini**.

Die Lib ist jedoch von den Timings her auf 8MHz ausgelegt.
Da der 16MHz-Arduino nun alles doppelt so schnell rechnet, wirst du das nicht sauber zum Laufen bekommen.

Daher auch der Hinweis in der README fettgedruckt: **ATmega328P (3.3V / 8MHz)**

Du kannst versuchen, das delay zwischen den beiden Telegrammen zu verdoppeln.
[HB-UNI-Sen-TEMP-DS18B20.ino#L145](https://github.com/jp112sdl/HB-UNI-Sen-TEMP-DS18B20/blob/7b6502f7c7ed16385bb2d235ee7eceb012a968a0/HB-UNI-Sen-TEMP-DS18B20/HB-UNI-Sen-TEMP-DS18B20.ino#L145)
`_delay_ms(200);` -> `_delay_ms(400);`

**Comment by jp112sdl** [comment]
Ich rate beim 16MHz Pro Mini auch dringend von Batteriebetrieb ab!

**Comment by isolhara** [comment]
Ok, besten Dank. Ich habe zwei Arduino 3,3V 8 MHz bei EBay (China) gekauft. Versuche nun einen wirklichen 3,3V 8MHz zu bekommen, leider ist es auf dem Arduino selbst nicht zu sehen. Ich habe bereits ein Spannungsreglermodul 3,3 V ausprobiert.

**Comment by jp112sdl** [comment]
Auf dem Oszillator steht beim 8MHz Pro Mini eine **80** oder **08** (je nachdem wie rum man drauf schaut):
<img width="624" alt="bildschirmfoto 2018-07-16 um 21 46 45" src="https://user-images.githubusercontent.com/18190139/42779807-c2fc4cf8-8941-11e8-899c-242d21066927.png">

Bei dem 16MHz Modell steht da glaub ich **A0**.

Das Problem ist, dass der 328P bei 16MHz mind. 4,3V benötigt, um stabil zu laufen.

**Comment by isolhara** [comment]
Das delay hatte ich schon mal auf 500 ms gesetzt, hatte nichts gebracht. Für mich nicht erklärlich, wenn ich zuerst 5 - 8  in meinem Fall den Sensor 5 sende, dann die Sensoren 1 - 4 nicht mehr gesendet werden. Folglich müsste doch die Übertragung als solches funktionieren.

**Comment by jp112sdl** [comment]
Schick mal die Logmeldungen vom Einschalten bis zur Übertragung der 2 Telegramme...

**Comment by isolhara** [comment]
Wo finde ich diese Logmeldungen?

**Comment by jp112sdl** [comment]
...immer noch im seriellen Monitor

**Comment by isolhara** [comment]
![image](https://user-images.githubusercontent.com/30491957/42780955-06b55c98-8945-11e8-8bab-bae55a7d8cb3.png)

**Comment by isolhara** [comment]
![image](https://user-images.githubusercontent.com/30491957/42781120-88492a8c-8945-11e8-82a9-c5fc5cdf0348.png)

**Comment by jp112sdl** [comment]
Also zunächst mal ist das Device nicht korrekt angelernt.
Bitte noch mal löschen und neu anlernen.

Und ändere mal das delay auf 300.

**Comment by jp112sdl** [comment]
Bei `F30101 000000` muss dort statt der `000000` die ID von der CCU drinstehen.

**Comment by isolhara** [comment]
![image](https://user-images.githubusercontent.com/30491957/42781890-a6c3a42c-8947-11e8-85d7-108ec42aadd4.png)

**Comment by isolhara** [comment]
Neu angelernt habe vorher nochmals geändert, dass zuerst 5-8 und dann 1-4 übertragen wird.

![image](https://user-images.githubusercontent.com/30491957/42782015-f096e5a0-8947-11e8-8af1-39ad4c13b799.png)

**Comment by jp112sdl** [comment]
Das sieht schon mal gut aus.
Aber du hast wieder die Telegramme umgedreht 😉 
Zuerst 5-8, dann 1-4

**Comment by jp112sdl** [comment]
Aber warum das in der WebUI nicht ankommt... ich kann mir da nur noch vorstellen, dass es am Timing liegt und dem 16MHz Pro Mini.
Bisher hat noch niemand einen solchen Fehler gemeldet

**Comment by isolhara** [comment]
Gibt es die Möglichkeit, das im WebUI zu protokollieren?

**Comment by jp112sdl** [comment]
Ich weiß nicht... Kannst ja mal das Gerät auf "Protokolliert" stellen.
Man könnte noch die Meldung vom `rfd` aber das führt hier alles zu weit.
Ich würde auch ungern noch weiter dran rumexperimentieren wollen, so lange nicht die Hardware eingesetzt wird, die offiziell unterstützt wird.
Tritt der Fehler mit einem echten 8MHz Pro Mini auf, können wir uns noch mal damit beschäftigen.
Ich kennen zumindest 2 weitere Leute, die die Schaltung mit 8 Sensoren erfolgreich im Einsatz haben.

Als letzten Versuch - statt das Delay zu erhöhen, setz es mal etwas herunter auf `100`.

**Comment by isolhara** [comment]
Ok, ja das war wirklich eine großartige Unterstützung. Ich besorge mir einen 8 MHz und gebe dann eine Rückmeldung.
Guten Abend

**Comment by jp112sdl** [comment]
Aber teste das mit den 100ms Delay trotzdem noch. Vielleicht gehts ja 👍 
Viel Erfolg weiterhin

**Comment by isolhara** [comment]
100 ms geht auch nicht, andere Arduino bereits bestellt.
Nochmals Danke.

**Comment by jp112sdl** [comment]
RaspberryMatic nochmals neustarten

**Comment by isolhara** [comment]
Danke das war's. Ich hatte auch schon RaspberryMatic neu gestartet, dann aber immer versucht das Gerät neu anzulernen. Jetzt habe ich einfach gewartet. 
Auf dem alten Arduino steht auf dem Quarz keine Frequenzangabe. Die neuen sind richtig beschriftet.
Nochmals besten Dank für die Hilfe.
