### ISSUE TITLE
One-Wire Pull Up Widerstand

### ISSUE THREAD

**Issue by spaceduck518** [jp112sdl/HB-UNI-Sen-TEMP-DS18B20#4]
Ich habe 8 Sensoren über ca. 10m Kabel angeschlossen und musste den Pullup von 4,7k auf 2,2k ändern um ein stabiles reading zu bekommen. Vermutlich würden auch 3,3k gehen, aber 4,7k scheint bei langen Leitungen grenzwertig zu sein.

**Comment by jp112sdl** [comment]
Bei Wiki steht auch was von 2,2k
https://de.wikipedia.org/wiki/1-Wire#Elektrische_Eigenschaften

**Comment by jp112sdl** [comment]
Habs in der Teileliste der README geändert.
Danke!
