### ISSUE TITLE
Nach "Found x DS18B20 Sensor" keine Aktion mehr

### ISSUE THREAD

**Issue by Fiiti** [jp112sdl/HB-UNI-Sen-TEMP-DS18B20#7]
Hi,
bei mir bleibt nach dieser Ausgabe alles stehen:

> AskSin++
> 
>  V3.1.2 (Dec 25 2018 13:02:49)
> ID: F30101  Serial: UNITEMP001
> Address Space: 32 - 335
> CC init1
> CC Version: 14
>  - ready
> Bat: 35
> Found 2 DS18B20 Sensors
> 

Es passiert auch nichts, wenn ich auf den Button zum Anlernen drücke.

Zum Testen der Hardware hatte ich den Sketch https://github.com/jp112sdl/Beispiel_AskSinPP/tree/master/examples/HM-WDS40-TH-I-BME280 erfolgreich verwenden können. Natürlich auch mit entsprechenden anderem Sensor.
Lief erfolgreich mit der CCU3.

Ich nutze18b20 Sensoren, der Serielle Monitor zeigt auch die richtige Anzahl an. Bei einem 1, bei 2 zwei, usw.

Habe alle Leiterbahnen nachgemessen, auf kurzschlüsse untersucht usw. 
Irgendeine Idee, wo ich noch schauen könnte?

Viele Grüße,
Fi

**Comment by Fiiti** [comment]
Wenn ich den Sketch HM-WDS40-TH-I-DS18B20 mit den gleichen Sensoren nehme, dann kommt erfolgreich diese Ausgabe:
> AskSin++ V3.1.2 (Dec 25 2018 13:37:02)
> Address Space: 32 - 73
> CC init1
> CC Version: 14
>  - ready
> Bat: 35
> Measure...
> T/H = 258/0
> <- 0C 01 84 70 345681 000000 01 02 00  - 1804
> Measure...
> T/H = 258/0
> <- 0C 02 84 70 345681 000000 01 02 00  - 2588

Hier wird der #include <DallasTemperature.h> verwendet - in Deinem nicht. Sondern anscheinend der #include <sensors/Ds18b20.h>
Mal schauen ob ich hier was finde.

**Comment by jp112sdl** [comment]
Hi,

ich kanns leider auch auch nicht nachvollziehen.

Nach dem 
`Found 2 DS18B20 Sensors`
kommt auch eigentlich nichts weiter.
Es wird die sysclock aktiviert, die 5 Sekunden später den Alarm im `sensarry` triggert.

Du kannst dir hilfweise mal noch eine Debugausgabe vor der Messung einbauen, um zu schauen, ob es wirklich was mit der Ds18b20.h zu tun hat.
z.B. [hier](https://github.com/jp112sdl/HB-UNI-Sen-TEMP-DS18B20/blob/master/HB-UNI-Sen-TEMP-DS18B20/HB-UNI-Sen-TEMP-DS18B20.ino#L144) noch ein `DPRINTLN("jetzt wird gemessen...");`.

**Comment by Fiiti** [comment]
Danke.
Es blieb in der LCD Ausgabe stehen - obwohl diese nicht definiert war.
Ich habe dann schlussendlich alles gleöscht, neu kopiert, neu angelegt und alles lief sofort. Ob es nun der Kompiler, IDE oder ein Level 8 Problem war, werde ich nicht herausfinden.
Gute Arbeit - danke dafür!

Issue kann geschlossen werden.

**Comment by jp112sdl** [comment]
Alles klar 👍 
Es funktioniert nun also mit dem Code ausm Github 1:1, oder hast du noch was angepasst?

**Comment by Fiiti** [comment]
Genau. Ich folgte dem Link von dir in deiner ersten Antwort. Habe dann RAW Ansicht ausgewählt.
Da habe ich den Code 1:1 kopiert und in der arduino IDE eingefügt. Kompiliert , hochgeladen und es lief sofort.
Den ersten Code habe ich irgendwie durch einen kompletten Download geholt bin git geholt.
Da bin ich über Links von technikkram gekommen.
Vielleicht ist auch hier der Fehler?

Egal, dein Code Funktioniert super und ich bin schwer begeistert.

Einzig würde ich mir wünschen, dass wenn weitere Sensoren angeschlossen werden, was ja problemlos im laufenden Betrieb ohne Reset bestens funktioniert, die bereits vorhandenen an der Position bleiben, wo sie waren.
Bsp: Hatte nur einen Sensor dann, in Ccu war dieser auf Position 1.
Jetzt steckte ich einen weiteren ran, und schwupps war der Alte auf Position 2 in der Ccu gerutscht. Der neue ist nun auf Platz 1.
Aber das ist jammern auf hohem Niveau. Kann mir nur vorstellen, dass bei einigen zu Problemen führen kann, wenn z.b. Programme diese Sensoren nutzen.
Man merkt es ja nicht gleich bei ähnlichen Produkten.

**Comment by jp112sdl** [comment]
Es gab in der Richtung schon mal einen Ansatz von einem anderen Anwender. 
Ich habe es aber nicht weiter verfolgt, da ich es eher so sehe, dass man ja ein Projekt mit x Sensoren umsetzt, dieses fertig baut und dann anlernt.
Da ändert sich dann nix mehr.
Ggf. könnte man noch die I2C-Adressen seriell ausgeben, so dass man im seriellen Monitor sehen kann, an welcher Position welcher Sensor erkannt wird und um dann bei Verschiebungen unkomplizierter reagieren zu können.

**Comment by Fiiti** [comment]
Das ist eine gute Idee, werde ich vielleicht mal umsetzen, kann es ja pullen/pushen oder was auch immer, komme immer noch etwas mit Git durcheinander :-)
Soll ich schließen oder möchtest Du? Das scheint ein jeder auf Git anders handhaben zu wollen.

**Comment by jp112sdl** [comment]
Das ist mir egal... Wenn gelöst, dann gelöst 👍 
Und zu... 😃
